//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parser.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parser.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Log Parser created by Maple for GTA World.
        ///
        ///Installed Version: {0}
        ///
        ///Would you like to visit the repository page on GitHub?.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Backup: {0}.
        /// </summary>
        internal static string BackupStatus {
            get {
                return ResourceManager.GetString("BackupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic backup has been turned OFF, please set it up again if you wish to use it..
        /// </summary>
        internal static string BackupTurnedOff {
            get {
                return ResourceManager.GetString("BackupTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The automatic backup function will be turned off while the settings dialog is open and the new settings will only be applied once you close the settings dialog.
        ///
        ///Would you like to continue?.
        /// </summary>
        internal static string BackupWillBeOff {
            get {
                return ResourceManager.GetString("BackupWillBeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick a non-root directory for your RAGEMP folder location..
        /// </summary>
        internal static string BadFolderPath {
            get {
                return ResourceManager.GetString("BadFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters and {1} lines.
        /// </summary>
        internal static string CharacterCounter {
            get {
                return ResourceManager.GetString("CharacterCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to delete the file..
        /// </summary>
        internal static string FileDeleteError {
            get {
                return ResourceManager.GetString("FileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically found your RAGEMP folder at {0}
        ///
        ///Please browse for the correct path manually if this is incorrect or you have multiple RAGEMP installations..
        /// </summary>
        internal static string FolderFinder {
            get {
                return ResourceManager.GetString("FolderFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to automatically find the location of your RAGEMP folder, please browse for it manually..
        /// </summary>
        internal static string FolderFinderError {
            get {
                return ResourceManager.GetString("FolderFinderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t detect the path to your RAGEMP folder, please browse for it manually..
        /// </summary>
        internal static string FolderFinderNotFound {
            get {
                return ResourceManager.GetString("FolderFinderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information (First Start).
        /// </summary>
        internal static string FolderFinderTitle {
            get {
                return ResourceManager.GetString("FolderFinderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RAGEMP folder path..
        /// </summary>
        internal static string InvalidFolderPath {
            get {
                return ResourceManager.GetString("InvalidFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a valid RAGEMP folder location before trying to enable automatic backup..
        /// </summary>
        internal static string InvalidFolderPathBackup {
            get {
                return ResourceManager.GetString("InvalidFolderPathBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a valid RAGEMP folder location before trying to filter your chat log..
        /// </summary>
        internal static string InvalidFolderPathFilter {
            get {
                return ResourceManager.GetString("InvalidFolderPathFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 164.132.206.209_22005.
        /// </summary>
        internal static string MainIP {
            get {
                return ResourceManager.GetString("MainIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing the parser will prevent the automatic backups from happening.
        ///
        ///Would you like to minimize the parser to the system tray instead?.
        /// </summary>
        internal static string MinimizeInsteadOfClose {
            get {
                return ResourceManager.GetString("MinimizeInsteadOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple GTA World resource directories were found. It is advised you use a single IP to connect to the server and delete the other resource directory.
        ///
        ///Keep either &quot;{0}&quot; or &quot;{1}&quot;..
        /// </summary>
        internal static string MultipleChatLogs {
            get {
                return ResourceManager.GetString("MultipleChatLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the GTA World chat log..
        /// </summary>
        internal static string NoChatLog {
            get {
                return ResourceManager.GetString("NoChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates could be found, try checking your internet connection.
        ///
        ///Installed Version: {0}.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t parsed anything yet..
        /// </summary>
        internal static string NothingParsed {
            get {
                return ResourceManager.GetString("NothingParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An old format was detected while parsing the chat log and it is advised you delete it and all other scripts that didn&apos;t update correcly.
        ///
        ///Would you like to delete these files?
        ///(The chat log file will be parsed before deletion).
        /// </summary>
        internal static string OldChatLog {
            get {
                return ResourceManager.GetString("OldChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to open the documentation page for the chat log parser found on the GTA World forums?.
        /// </summary>
        internal static string OpenDocumentation {
            get {
                return ResourceManager.GetString("OpenDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing the chat log..
        /// </summary>
        internal static string ParseError {
            get {
                return ResourceManager.GetString("ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser needs to restart in order to apply the selected language.
        ///
        ///Would you like to apply the language and restart the application now?.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string RestartTitle {
            get {
                return ResourceManager.GetString("RestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version of the chat log parser.
        ///
        ///Installed Version: {0}.
        /// </summary>
        internal static string RunningLatest {
            get {
                return ResourceManager.GetString("RunningLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to save the file..
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.gta.world_22005.
        /// </summary>
        internal static string SecondaryIP {
            get {
                return ResourceManager.GetString("SecondaryIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings will only be applied once you close the settings dialog..
        /// </summary>
        internal static string SettingsAfterClose {
            get {
                return ResourceManager.GetString("SettingsAfterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the chat log parser is now available on GitHub.
        ///
        ///Installed Version: {0}
        ///Available Version: {1}
        ///
        ///Would you like to visit the releases page now?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
